### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by Dadkins918** [Viren070/stremio-gdrive-addon#1]
I keep getting Error 400: redirect_uri_mismatch
I feel like I have followed the steps, I must be missing something?

**Comment by Viren070** [comment]
Is your OAuth client type `web application` and have you added `https://guides.viren070.me/oauth/google/callback` to your Authorized redirect URIs like this?:

![image](https://github.com/user-attachments/assets/3f5d27de-95ef-4179-9749-bf9c8a6dd72b)

if you have, then i'll add some logging so we can try and debug.

**Comment by Dadkins918** [comment]
Yes I went back to make sure.

**Comment by Dadkins918** [comment]
I just realized that URL is different.  Has it been changed or did I copy it from the wrong page?  I will retry with this one.

**Comment by Viren070** [comment]
ah, yeah, I moved it to its separate page to make it easier. Sorry about that, I was still in the process of improving it.

**Comment by Viren070** [comment]
oh i see why, I haven't updated the screenshot in the guide that has the old link. I'll get that updated soon.

**Comment by Dadkins918** [comment]
Can't remember exactly, think it had a path like /stremio/addons or something in it.  That was the issue, though.  Thank you!

**Comment by Viren070** [comment]
yeah no worries. also let me know if you have any issues with the addon, I haven't been able to test much.
